name: scan
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image tag, format image:tag"
        required: true
        type: string
        default: node:20-alpine
      severities:
        description: "Comma-separated list of severities to scan for: critical, high, medium, low, unspecified"
        required: false
        type: string
        default: critical,high
      package-types:
        description: "Comma-separated list of package types to scan for: e.g. apk, nuget or empty for all"
        required: false
        type: string
        default: "npm"
jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Build
        run: docker pull ${{ inputs.image_tag }}
      - name: Scan
        uses: felipecruz91/scout-action@817f0537bb54c64dd3d45cd0e721a64694b0686d
        with:
          command: cves,recommendations
          image: local://${{ inputs.image_tag }}
          only-severities: ${{ inputs.severities || 'critical,high' }}
          only-package-types: ${{ inputs.package-types || '' }}
          only-fixed: true
          summary: true
          format: json
          exit-code: true
